### ISSUE TITLE
Syntax highlighting not applied with regex-rules using another regex-rule

### ISSUE THREAD

**Issue by ssrmm** [rsdn/nitra#14]
The following grammar does not produce any syntax highlighting for the keywords `FLOAT` and `INTEGER` even though it should.
```C#
namespace Test
{
  syntax module Test
  {
    using Nitra.Core;

    [StartRule]
    syntax Expressions = (Keyword sm IdentifierBody ';' nl)+;

    regex Keyword = Keyword_FLOAT | Keyword_INTEGER;

    [SpanClass(Keyword)] regex Keyword_FLOAT = "FLOAT";
    [SpanClass(Keyword)] regex Keyword_INTEGER = "INTEGER";
  }
}
```
As a workaround one must add ` [SpanClass(Keyword)]` directly to `regex Keyword` which might not always be desirable.

**Comment by rampelstinskin** [comment]
regex don't have any information about it internals.
Use token or syntax keyword for "Keyword" rule.

**Comment by ssrmm** [comment]
Makes sense, now that you say it...
