### ISSUE TITLE
Create VS addin project skeleton

### ISSUE THREAD

**Issue by vasily-kirichenko** [rsdn/nitra#4]
- [x] Create an empty VS extension project in VS 2013, targeting VS 2013 and VS 2015
- [x] Place all referenced assemblies into a folder inside the repository
- [x] Make it build on a machine without any VS SDK installed
- [x] Create a couple of scripts
 - [x] Builds the project (result: VSIX file)
 - [x] Same as above + install (register) the VSIX into all installed VS versions

**Comment by vasily-kirichenko** [comment]
@VladD2 I cannot find any code which registers the Nemerle VSIX in *all* VS versions. What I've found is a bunch per-VS-version scripts. What they do is simply calling

`"%VS140COMNTOOLS%\..\IDE\VSIXInstaller.exe" /q "%NemerleInstall%\Nemerle.VisualStudio.vsix"`

see https://github.com/rsdn/nemerle/blob/master/Reg-bins-VS2015.cmd#L60

**Comment by NN---** [comment]
It is done using WiX.
See here: https://github.com/rsdn/nemerle/tree/master/misc/packages/wix/Sources

Vs2010_Extension.wxs this file contains all VS versions.

**Comment by vasily-kirichenko** [comment]
Wow. It looks like a lot of stuff done in a weird unreadable scripting language. 

We certainly should not use WiX for this task. We need a good statically typed scripting language. Suggestions?

**Comment by NN---** [comment]
The simplest is to use environment variable and VSIXInstaller.
It is the best way to install extensions.

You can also just copy if you don't want VSIXInstaller; http://blogs.msdn.com/b/saraford/archive/2010/03/11/how-to-install-visual-studio-extensions.aspx

I suggest to make a normal installer using WiX , then you don't need to worry about it.

**Comment by vasily-kirichenko** [comment]
The problem that vsixinstaller may not be found on user machine.

@VladD2 found this tiny piece of code to install VSIX into any named (/rootsuffix) VS instance https://github.com/SLaks/Root-VSIX 

I'm going to create a msbuild Task based on that code and use it in a *.build file.

**Comment by vasily-kirichenko** [comment]
To clarify things: this issue is about creating an automating script _for a Nitra user_ (and for us, of course while we debugging the template). The flow may look like this:

* user creates and builds his language (*.dll) 
* user launches `make_and_register_vs_addin.cmd <path to the lang dll> <VS rootsuffix - optional>`

Results:

* VSIX project is generated/updated (by calling Nitra.LanguageCompiler.exe)
* The project ^ is build (msbuild <generated project name>)
* VSIX is unregistered from <root suffix> instances of all versions of VS found on user's machine
* VSIX is registered in the same set of VS version/instances as above ^

**Comment by vasily-kirichenko** [comment]
Done here https://github.com/vasily-kirichenko/StandaloneVsix

**Comment by vasily-kirichenko** [comment]
Now we need to decide where it should be put in this repository and what stuff should go into NuGet package(s).

**Comment by vasily-kirichenko** [comment]
Further discussion will be in the PR https://github.com/rsdn/nitra/pull/5
