### ISSUE TITLE
[VS Plugin] Some error messages are not displayed

### ISSUE THREAD

**Issue by ssrmm** [rsdn/nitra#49]
Some of the produced error messages are not shown in Visual Studio. Consider the following example with the C# grammar
```C#
namespace CSharp
{
    public class Program
    {}
    
    public class Program
    {}
    
    public class Tester
    {
        public Program Test()
        {
            throw new System.NotImplementedException();
        }
    }
}
```

Inside Visual Studio this produces only one error message:
```
Symbol 'Program' is ambiguous.
```

In the visualizer however the same program and the same grammar produce a total of 8 errors:

![Visualizer Errors](https://cloud.githubusercontent.com/assets/22149188/22108348/02d85ae2-de53-11e6-9141-77eb3a56cb82.png)

That means currently only error message 3 is shown in VisualStudio. However, error messages 1, 2, 4 and 5 should also be displayed. Messages 6, 7 and 8 seem to be a minor bug in the grammar or the visualizer and shouldn't be relevant for this.

**Comment by VladD2** [comment]
The problem is that VS interface is not designed to display hierarchy of errors. We can show it in hints and as separate records in the Error window.

**Comment by ssrmm** [comment]
Yeah, I guess it doesn't make much sense when the sub-errors appear out of context. I'm pretty sure I've seen VS do something similar in one case, but really can't remember what it was...

The `Redefinition of 'Program'` should be displayed, though.

**Comment by VladD2** [comment]
I try to set [MaintainInitialTaskOrder](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.taskprovider.maintaininitialtaskorder.aspx) property of the ErrorListProvider, but in has no effect. 
The VS Error list does not call [IVsTaskProvider2.MaintainInitialTaskOrder()](https://msdn.microsoft.com/cs-cz/library/microsoft.visualstudio.shell.interop.ivstaskprovider2.maintaininitialtaskorder.aspx) and always use sorting. :(
I think that under these conditions, show nested messages in the Error list does not make sense.

**Comment by VladD2** [comment]
Apparently I have to change the whole design.
I should make one message which include all information. And to make navigation through a pop up hint.
Too much work. :(

**Comment by VladD2** [comment]
I solved this problem by improve the hint and the error message.
![Screenshot](http://files.rsdn.org/73/Nitra/Nitra-006.gif)
